version: 1

policy:
  default:
    min: 80
  domains:
    - name: cmd
      match:
        - ./cmd/...
      min: 64  # Lower threshold: many tests skip when engines not installed in CI
    - name: application
      match:
        - ./internal/application/...
      min: 78  # Lower threshold: engine-dependent code paths not covered in CI
    - name: domain
      match:
        - ./internal/domain/...
      min: 80
    - name: infrastructure
      match:
        - ./internal/infrastructure/...
      min: 80
    - name: pkg
      match:
        - ./pkg/...
      min: 80
