version: 1

policy:
  default:
    min: 50
  domains:
    - name: cmd
      match:
        - ./cmd/...
      min: 31  # CLI command wiring, many paths skip when engines not installed
    - name: application
      match:
        - ./internal/application/...
      min: 50  # Use cases with engine-dependent code paths
    - name: domain
      match:
        - ./internal/domain/...
      min: 75  # Core domain logic - highest priority
    - name: infrastructure
      match:
        - ./internal/infrastructure/...
      min: 53  # External integrations, many require real tools (includes TUI with limited test coverage)
    - name: pkg
      match:
        - ./pkg/...
      min: 80  # Utility packages - well tested
