version: "2"

linters:
  default: standard
  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Chdir
        - (*os.File).Chdir
    staticcheck:
      checks:
        - "all"
        - "-SA1012"
        - "-S1009"
        - "-S1011"
        - "-QF1003"
        - "-ST1000"
        - "-ST1003"
